---
- name: "before chocomilk"
  hosts: chocomilk
  connection: local
  gather_facts: false
  tasks:
    - name: "install pip package"
      become: true
      pip:
        name:
          - docker
          - lxml
          - jmespath
